// swift-tools-version:5.9
//
// Manifest for the Token Meter macOS app (plan:
// .omo/plans/token-meter-macos-app.md).
//
// RED phase (node `swift-red`) declared TokenMeterCore, TokenMeterApp and
// the test target with no production sources; `swift test` failed because
// the TokenMeterCore production module had no sources, not because of
// manifest or test-harness defects.
//
// GREEN wave (nodes `swift-core-green` / `swift-ui-green`) fills in
// Sources/TokenMeterCore and Sources/TokenMeterApp; the test contracts in
// Tests/TokenMeterCoreTests are already final and must not need edits.
//
// `swift-core-green` writes Sources/TokenMeterCore only. SwiftPM refuses to
// build a source-less executable target, so TokenMeterApp is included
// exactly when its sources exist — a minimal manifest extension required by
// the otherwise-failing empty target. Node `swift-ui-green` adds
// Sources/TokenMeterApp and the target activates unchanged; no UI files are
// written by the core wave.
import Foundation
import PackageDescription

let appTargetHasSources = FileManager.default.fileExists(atPath: "Sources/TokenMeterApp")

var targets: [Target] = [
    .target(
        name: "TokenMeterCore",
        resources: [
            // Canonical capability registry: generated by
            // bridge/scripts/sync-omp-registry.ts and shipped byte-identical
            // to bridge/generated/provider-capabilities.json.
            .process("Resources/provider-capabilities.json")
        ]
    ),
    .testTarget(
        name: "TokenMeterCoreTests",
        dependencies: [
            .target(name: "TokenMeterCore")
        ]
    ),
]

if appTargetHasSources {
    targets.append(
        .executableTarget(
            name: "TokenMeterApp",
            dependencies: [
                .target(name: "TokenMeterCore")
            ]
        )
    )
    targets.append(
        .testTarget(
            name: "TokenMeterAppTests",
            dependencies: [
                .target(name: "TokenMeterApp"),
                .target(name: "TokenMeterCore"),
            ]
        )
    )
}

let package = Package(
    name: "token-meter",
    platforms: [
        .macOS(.v14)
    ],
    targets: targets
)
