// Locked provider capability catalog — manifest registry 1.2.0.
//
// There is exactly one shipped capability contract: the packaged resource
// Sources/TokenMeterCore/Resources/provider-capabilities.json, generated by
// the bridge's OMP sync (bridge/scripts/sync-omp-registry.ts) from the
// locked registry in bridge/src/registry.ts and byte-identical to
// bridge/generated/provider-capabilities.json. `ProviderCatalog.locked`
// strictly decodes that resource through Bundle.module at runtime; no
// hand-written capability table exists on the Swift side. The only Swift-owned
// presentation metadata kept beside it is the display-name map below.
//
// Entries carry capability and support metadata only: support tier, connector
// transport, login methods, credential kinds, product/source kinds,
// authorization basis and polling policy. There is no model catalog anywhere
// — strict decoding rejects every unknown or model-shaped field.
import Foundation

/// A CodingKey that accepts any string. Typed CodingKeys silently hide
/// unknown keys from `allKeys`, so strict decoding validates the real key
/// set through this pass-through key first.
struct StrictCodingKey: CodingKey {
    var stringValue: String
    var intValue: Int?

    init?(stringValue: String) {
        self.stringValue = stringValue
        self.intValue = nil
    }

    init?(intValue: Int) {
        return nil
    }
}

enum StrictKeys {
    static func present(_ decoder: Decoder) throws -> Set<String> {
        let container = try decoder.container(keyedBy: StrictCodingKey.self)
        return Set(container.allKeys.map(\.stringValue))
    }

    static func nestedPresent<K: CodingKey>(
        _ container: KeyedDecodingContainer<K>,
        key: K
    ) throws -> Set<String> {
        let nested = try container.nestedContainer(keyedBy: StrictCodingKey.self, forKey: key)
        return Set(nested.allKeys.map(\.stringValue))
    }

    static func requireExact(
        _ present: Set<String>,
        required: Set<String>,
        codingPath: [CodingKey]
    ) throws {
        guard present == required else {
            let unknown = present.subtracting(required).sorted()
            throw DecodingError.dataCorrupted(.init(
                codingPath: codingPath,
                debugDescription: unknown.isEmpty
                    ? "missing fields \(required.subtracting(present).sorted())"
                    : "unknown fields \(unknown)"
            ))
        }
    }
}

// MARK: - Registry vocabulary (manifest 1.2.0)

public enum RegistrySupportTier: String, Codable, Equatable, Sendable, CaseIterable {
    case supported
    case bestEffort
    case conditional
    case excluded
}

/// Legacy three-way support tier retained only to keep the current app
/// target compiling until its later catalog rework.
public enum SupportTier: String, Codable, Equatable, Sendable, CaseIterable {
    case supported
    case experimental
    case metadataOnly
}

/// Connector dispatch vocabulary. `builtin-<connectorId>` names a bundled
/// provider module; `external` names a future out-of-process transport.
public enum ConnectorTransport: Equatable, Sendable {
    case builtin(String)
    case external

    public var wireValue: String {
        switch self {
        case .builtin(let connectorId): return "builtin-\(connectorId)"
        case .external: return "external"
        }
    }
}

extension ConnectorTransport: Codable {
    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        if raw == "external" {
            self = .external
            return
        }
        let prefix = "builtin-"
        guard raw.hasPrefix(prefix), raw.count > prefix.count else {
            throw DecodingError.dataCorrupted(.init(
                codingPath: decoder.codingPath,
                debugDescription: "unknown connector transport: \(raw)"
            ))
        }
        self = .builtin(String(raw.dropFirst(prefix.count)))
    }

    public func encode(to encoder: Encoder) throws {
        var single = encoder.singleValueContainer()
        try single.encode(wireValue)
    }
}

public enum AuthorizationBasis: String, Codable, Equatable, Sendable, CaseIterable {
    case documentedUserBilling
    case subscriptionOAuth
    case apiKey
    case browserSession
    case deviceNone
    case unreviewed
}

public enum PollingPolicy: String, Codable, Equatable, Sendable, CaseIterable {
    case authorizedDefault
    case notPolled
}

public enum DeclaredWindow: String, Codable, Equatable, Sendable, CaseIterable {
    case threeHour = "3h"
    case fiveHour = "5h"
    case sevenDay = "7d"
    case daily
    case weekly
    case monthly
}

public enum RegistryProductKind: String, Codable, Equatable, Sendable, CaseIterable {
    case quota
    case billingUsage
    case organizationUsage
    case localActivity
    case unreviewed
}

public enum RegistrySourceKind: String, Codable, Equatable, Sendable, CaseIterable {
    case localObserved
    case documentedApi
    case firstPartyApi
    case privateApi
    case browserSession
    case noQuotaApi
    case unreviewed
}

// MARK: - Capability entry

public struct ProviderCapability: Equatable, Sendable, Codable {
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case registrySupportTier = "supportTier"
        case connectorTransport
        case authMethods
        case credentialKinds
        case productKind
        case sourceKind
        case authorizationBasis
        case declaredUnit
        case declaredWindows
        case pollingPolicy
    }

    public let id: String
    public let registrySupportTier: RegistrySupportTier
    public let connectorTransport: ConnectorTransport
    public let authMethods: [AuthMethod]
    public let credentialKinds: [CredentialKind]
    public let productKind: RegistryProductKind
    public let sourceKind: RegistrySourceKind
    public let authorizationBasis: AuthorizationBasis
    public let declaredUnit: UsageUnit
    public let declaredWindows: [DeclaredWindow]
    public let pollingPolicy: PollingPolicy

    public init(
        id: String,
        registrySupportTier: RegistrySupportTier,
        connectorTransport: ConnectorTransport,
        authMethods: [AuthMethod],
        credentialKinds: [CredentialKind],
        productKind: RegistryProductKind,
        sourceKind: RegistrySourceKind,
        authorizationBasis: AuthorizationBasis,
        declaredUnit: UsageUnit,
        declaredWindows: [DeclaredWindow],
        pollingPolicy: PollingPolicy
    ) {
        self.id = id
        self.registrySupportTier = registrySupportTier
        self.connectorTransport = connectorTransport
        self.authMethods = authMethods
        self.credentialKinds = credentialKinds
        self.productKind = productKind
        self.sourceKind = sourceKind
        self.authorizationBasis = authorizationBasis
        self.declaredUnit = declaredUnit
        self.declaredWindows = declaredWindows
        self.pollingPolicy = pollingPolicy
    }

    /// Non-secret display metadata pinned in-process; the synchronized
    /// registry deliberately carries no display-name field.
    public var displayName: String {
        ProviderCatalog.displayNames[id] ?? id
    }

    /// Compatibility projection for the current app's three-way display.
    /// The full 1.2.0 value is always available as `registrySupportTier`.
    @available(*, deprecated, message: "use registrySupportTier")
    public var supportTier: SupportTier {
        switch registrySupportTier {
        case .supported: return .supported
        case .bestEffort: return .experimental
        case .conditional, .excluded: return .metadataOnly
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        try StrictKeys.requireExact(
            try StrictKeys.present(decoder),
            required: Set(CodingKeys.allCases.map(\.stringValue)),
            codingPath: decoder.codingPath
        )
        id = try container.decode(String.self, forKey: .id)
        registrySupportTier = try container.decode(RegistrySupportTier.self, forKey: .registrySupportTier)
        connectorTransport = try container.decode(ConnectorTransport.self, forKey: .connectorTransport)
        authMethods = try container.decode([AuthMethod].self, forKey: .authMethods)
        credentialKinds = try container.decode([String].self, forKey: .credentialKinds).map { raw in
            guard let kind = CredentialKind(rawValue: raw) else {
                throw DecodingError.dataCorrupted(.init(
                    codingPath: decoder.codingPath + [CodingKeys.credentialKinds],
                    debugDescription: "unknown credential kind: \(raw)"
                ))
            }
            return kind
        }
        productKind = try container.decode(RegistryProductKind.self, forKey: .productKind)
        sourceKind = try container.decode(RegistrySourceKind.self, forKey: .sourceKind)
        authorizationBasis = try container.decode(AuthorizationBasis.self, forKey: .authorizationBasis)
        declaredUnit = try container.decode(UsageUnit.self, forKey: .declaredUnit)
        declaredWindows = try container.decode([DeclaredWindow].self, forKey: .declaredWindows)
        pollingPolicy = try container.decode(PollingPolicy.self, forKey: .pollingPolicy)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(registrySupportTier, forKey: .registrySupportTier)
        try container.encode(connectorTransport, forKey: .connectorTransport)
        try container.encode(authMethods, forKey: .authMethods)
        try container.encode(credentialKinds.map(\.rawValue), forKey: .credentialKinds)
        try container.encode(productKind, forKey: .productKind)
        try container.encode(sourceKind, forKey: .sourceKind)
        try container.encode(authorizationBasis, forKey: .authorizationBasis)
        try container.encode(declaredUnit, forKey: .declaredUnit)
        try container.encode(declaredWindows, forKey: .declaredWindows)
        try container.encode(pollingPolicy, forKey: .pollingPolicy)
    }
}

// MARK: - Catalog

public struct ProviderCatalog: Equatable, Sendable, Codable {
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schemaVersion
        case syncedFromSha
        case providers
    }

    /// Registry manifest version; independent from the TokenMeter wire
    /// protocol version.
    public static let registrySchemaVersion = "1.2.0"

    public let schemaVersion: String
    public let syncedFromSha: String?
    public let providers: [ProviderCapability]

    public init(
        schemaVersion: String = ProviderCatalog.registrySchemaVersion,
        syncedFromSha: String? = nil,
        providers: [ProviderCapability]
    ) {
        self.schemaVersion = schemaVersion
        self.syncedFromSha = syncedFromSha
        self.providers = providers
    }

    /// Strict decode: unknown top-level fields (and, transitively, unknown
    /// or model-shaped provider fields) are rejected. Only `syncedFromSha`
    /// is optional.
    public init(decoding data: Data) throws {
        self = try JSONDecoder().decode(ProviderCatalog.self, from: data)
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let present = try StrictKeys.present(decoder)
        let required: Set<String> = [
            CodingKeys.schemaVersion.stringValue,
            CodingKeys.providers.stringValue,
        ]
        let allowed = required.union([CodingKeys.syncedFromSha.stringValue])
        guard present.isSuperset(of: required), present.isSubset(of: allowed) else {
            let unknown = present.subtracting(allowed).sorted()
            throw DecodingError.dataCorrupted(.init(
                codingPath: decoder.codingPath,
                debugDescription: unknown.isEmpty
                    ? "missing fields \(required.subtracting(present).sorted())"
                    : "unknown fields \(unknown)"
            ))
        }
        schemaVersion = try container.decode(String.self, forKey: .schemaVersion)
        guard schemaVersion == Self.registrySchemaVersion else {
            throw DecodingError.dataCorrupted(.init(
                codingPath: decoder.codingPath + [CodingKeys.schemaVersion],
                debugDescription: "unsupported registry schemaVersion: \(schemaVersion)"
            ))
        }
        syncedFromSha = try container.decodeIfPresent(String.self, forKey: .syncedFromSha)
        providers = try container.decode([ProviderCapability].self, forKey: .providers)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(schemaVersion, forKey: .schemaVersion)
        try container.encodeIfPresent(syncedFromSha, forKey: .syncedFromSha)
        try container.encode(providers, forKey: .providers)
    }
}

// MARK: - Locked set

public extension ProviderCatalog {
    /// Pinned OMP checkout the 16 OMP-derived capabilities were synchronized from.
    static let ompPinnedSHA = "8500092296621a6826b7136e840f8a59ea338958"

    /// Display-name metadata deliberately kept outside the registry wire;
    /// presentation only, never capability data.
    static let displayNames: [String: String] = [
        "alibaba-token-plan": "Alibaba Token Plan",
        "anthropic": "Anthropic",
        "cursor": "Cursor",
        "github-copilot": "GitHub Copilot",
        "google-antigravity": "Google Antigravity",
        "google-gemini-cli": "Google Gemini CLI",
        "kimi-code": "Kimi Code",
        "minimax-code": "MiniMax Code",
        "nekos": "Nekos Claude",
        "ollama": "Ollama",
        "ollama-cloud": "Ollama Cloud",
        "openai-codex": "OpenAI Codex",
        "opencode-go": "OpenCode Go",
        "synthetic": "Synthetic",
        "umans": "Umans",
        "xai-oauth": "xAI OAuth",
        "zai": "Z.ai",
    ]

    /// The 17 locked provider IDs (16 OMP-derived plus app-owned Nekos), unique and sorted.
    static let lockedProviderIds: [String] = locked.providers.map(\.id).sorted()

    /// The one shipped capability contract: the packaged registry resource,
    /// strictly decoded on first access. A missing or undecodable resource is
    /// a packaging defect, not a runtime condition the app can recover from.
    static let locked: ProviderCatalog = {
        let packagedBundle = Bundle.main.url(forResource: "token-meter_TokenMeterCore", withExtension: "bundle")
            .flatMap(Bundle.init(url:))
        let resourceBundle = packagedBundle ?? Bundle.module
        guard
            let url = resourceBundle.url(forResource: "provider-capabilities", withExtension: "json")
        else {
            fatalError("provider-capabilities.json is missing from the TokenMeterCore resource bundle")
        }
        do {
            return try ProviderCatalog(decoding: try Data(contentsOf: url))
        } catch {
            fatalError("packaged provider-capabilities.json failed strict decoding: \(error)")
        }
    }()
}
